# Имя сайта
site_name: My CV

# Настройки темы
theme:
  name: material  


# Настройки навигации
nav:
  - Главная: index.md
  - Опыт работы: experience.md
  - Навыки: skills.md
  - Образование: education.md
  - Контакты: contacts.md

# Дополнительные настройки
site_description: Мое профессиональное резюме и портфолио
site_author: Андрей Богун

# Настройки форматирования
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
